/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Rs485_send.h"
#include "Rs485_send_aliases.h"
#include "UART_RS_485.h"
#include "UART_RS_485_SPI_UART.h"
#include "UART_RS_485_PINS.h"
#include "UART_RS_485_SPI_UART_PVT.h"
#include "UART_RS_485_PVT.h"
#include "UART_RS_485_BOOT.h"
#include "UART_PC.h"
#include "UART_PC_SPI_UART.h"
#include "UART_PC_PINS.h"
#include "UART_PC_SPI_UART_PVT.h"
#include "UART_PC_PVT.h"
#include "UART_PC_BOOT.h"
#include "Timer.h"
#include "Clock_1.h"
#include "isr_Timer.h"
#include "Clock_2.h"
#include "Timer_from_pc.h"
#include "isr_Timer_from_pc.h"
#include "Timer_from_slave.h"
#include "isr_Timer_from_slave.h"
#include "UART_RS_485_SCBCLK.h"
#include "UART_RS_485_tx.h"
#include "UART_RS_485_tx_aliases.h"
#include "UART_RS_485_SCB_IRQ.h"
#include "UART_RS_485_rx.h"
#include "UART_RS_485_rx_aliases.h"
#include "UART_PC_SCBCLK.h"
#include "UART_PC_tx.h"
#include "UART_PC_tx_aliases.h"
#include "UART_PC_SCB_IRQ.h"
#include "UART_PC_rx.h"
#include "UART_PC_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

